# -*- coding: utf-8 -*-
"""СР1 14_09

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CJFLLPqYiNLDrjB4IDwArSeXAfvxs7sL
"""

import random

N = 100
M = 0
KL = 30
KN = 25
score = 0 #оценка за экзамен (от 0 до 3 решенных вопросов)

for o in range(0,N):
    all_tasks = []
    for i in range(1,31): #создание списка вопросов
        all_tasks.append(i)

    known_tasks = []
    for i in range(1,26): #заполнение списка известных вопросов
        x = random.choice(all_tasks)
        while x in known_tasks:
            x = random.choice(all_tasks)
        known_tasks.append(x)

    #print("All known tasks:")
    #for i in range(len(known_tasks)):
        #print(known_tasks[i])

    #print("Taken tickets:")
    for i in range(1, 4):
        task = random.choice(all_tasks)
        #print(task)
        if task in known_tasks:
            score += 1

    #print("Total score:")
    if score >= 2:
        M += 1
    #print(score)
    score = 0

print("Total resul of", N, "attempts:", M/N)